changeLogFile=src/main/resources/db/changelog/changes/001-baseline-schema.yaml
outputChangeLogFile=src/main/resources/db/changelog/changes/001-baseline-schema.yaml

url=JDBC:mysql://localhost:3306/barber_db
username=root
password=Lucas123
driver=com.mysql.cj.jdbc.Driver